### PR TITLE
Move methods into class pages for docs

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary

Moved the methods into class pages to speed up the building process of the documentation with the new ecosystem sphinx theme ([PR](https://github.com/qiskit-community/qiskit-nature/pull/1262)) following the steps made in https://github.com/Qiskit-Extensions/qiskit-experiments/pull/1231

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
I'll just reference the comment I made in qiskit-optimization for others that may see that since this is similar https://github.com/qiskit-community/qiskit-optimization/pull/563#issuecomment-1758229728

**Comment by mrossinek** [comment]
How does this impact the build time of the docs in the new theme? I.e. how will this change the times (and build sizes) reported in #1262 ?

**Comment by arnaucasau** [comment]
In this project, the speedup is noticeable. I have run locally the sphinx-build command with the version in #1262 and then adding the changes in this PR, and here are the results (time and size):

> **Version in #1262:**
> 604.91s (sphinx-build)
> 251 KB index.html size
> 39 MB total size
> 
> **Moving the docs into class pages:**
> 76.16s (sphinx-build)
> 65 KB index.html size
> 14.9 MB total size

**Review by mrossinek — APPROVED** [review]
Thanks for looking into this! :+1:

**Pull request merged**
