### PR TITLE
Use Qiskit Ecosystem theme

### PR DESCRIPTION
**Pull request by frankharkins**
### Summary

Updates to the new documentation theme. This is a draft PR to test docs build times.

 - Total file size increased by ~505% (5mb -> 27mb)
 - Build time increase by ~1512% (58s -> 877s)

### CODE REVIEW

**Comment by mrossinek** [comment]
> * Build time increase by ~1512% (58s -> 877s)

Just curious: are there any plans of addressing this? That build time is a bit excessive.

**Comment by Eric-Arellano** [comment]
> Just curious: are there any plans of addressing this? That build time is a bit excessive.

Yeah, this is still a draft because we first wanted to see how bad the hit was. For some repos, it's faster to use the new theme! For others like Qiskit or this repo, it's much slower naively.

We have a few techniques to work around this. Only haven't had time yet to implement it. We have an intern starting soon who we're hoping can help switch projects over :)

**Comment by mrossinek** [comment]
@frankharkins Given https://github.com/qiskit-community/qiskit-nature-pyscf/pull/44, can we expect this PR to move forward, too?
What do the timings look like with the latest version of the theme?

**Comment by Eric-Arellano** [comment]
@mrossinek, yes, @arnaucasau is a new intern at IBM and his first main project is to switch all the Ecosystem projects to the new theme 🙌 He's triaging if switching results in slow downs. When it does slow down, there are things we can do like reorganizing API docs to speed it up. He'll be helping projects out with that.

**Pull request closed without merging**
