### PR TITLE
Update Sphinx theme

### PR DESCRIPTION
**Pull request by arnaucasau**
### Summary
Updates to new Ecosystem theme.

Total file size increased (5.45 MB -> 7.18.7 MB)
index.html size increased (15 KB → 65 KB)
Build time increased (93s → 109s)

For more information: https://github.com/Qiskit/qiskit_sphinx_theme/issues/232

### CODE REVIEW

**Comment by mrossinek** [comment]
I do not see too big of an issue with the increase in file size.

> Build time increased (93s → 958s)

But this build time increase is pretty rough. I see that the main change under the hood was to switch to a different theme. But have other changes been made to the Sphinx setup? From the top of my head I could see that the use of different class documentation templates with or without inherited members might not work. This will cause _many_ dependencies to be pulled in (e.g. in the `qiskit_nature.second_q.circuit.library` classes) which has been a time-consuming process in the past, too.

Here are some potentially relevant PRs from the past:
- https://github.com/qiskit-community/qiskit-nature/pull/229
- https://github.com/qiskit-community/qiskit-nature/pull/1175

**Comment by Eric-Arellano** [comment]
> But this build time increase is pretty rough. I see that the main change under the hood was to switch to a different theme. But have other changes been made to the Sphinx setup?

Yeah, we know about it and Arnau will work on improvements. It's due to issues with Furo, the base theme we use. See https://github.com/Qiskit/qiskit_sphinx_theme/issues/328.

**Review by mrossinek — APPROVED** [review]
The updated build times after the merge of #1264 looks a lot more reasonable, thanks a lot!
Although I think there is a typo in the file size of the built docs, I am not too worried about that :+1:

**Comment by arnaucasau** [comment]
Thanks a lot @mrossinek, typo corrected!

**Comment by Eric-Arellano** [comment]
Thanks @mrossinek! Should Arnau cherry-pick these changes to stable/0.6? 

We're hoping to deploy the change soon because it's a priority to kill the old Pytorch theme with the Qiskit top nav bar (branding issue).

**Comment by mrossinek** [comment]
We can try backporting but I am honestly not sure about the state of the stable branch right now.
0.7 should be going out soon though, so if this is not required to be out before the end of October, waiting for up to 2 weeks is probably easiest for everyone.

**Pull request merged**
